/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author LAB4M10
 */
public class Abate_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Abate_GUI
     */
    public Abate_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        voltarAbate = new org.edisoncor.gui.button.ButtonAero();
        jPanel1 = new javax.swing.JPanel();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        IDAnimal_Abate = new javax.swing.JTextField();
        labelCustom2 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom3 = new org.edisoncor.gui.label.LabelCustom();
        IDGrupo_Abate = new javax.swing.JTextField();
        PesoAbate_Abate = new javax.swing.JFormattedTextField();
        labelCustom4 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom5 = new org.edisoncor.gui.label.LabelCustom();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fundo2.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        voltarAbate.setText("Voltar");
        voltarAbate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAbateActionPerformed(evt);
            }
        });
        panelImage1.add(voltarAbate);
        voltarAbate.setBounds(560, 360, 80, 25);

        jPanel1.setLayout(null);

        labelCustom1.setText("Peso Abate");
        jPanel1.add(labelCustom1);
        labelCustom1.setBounds(70, 260, 100, 30);

        IDAnimal_Abate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDAnimal_AbateActionPerformed(evt);
            }
        });
        jPanel1.add(IDAnimal_Abate);
        IDAnimal_Abate.setBounds(180, 140, 170, 30);

        labelCustom2.setText("ID Abate");
        jPanel1.add(labelCustom2);
        labelCustom2.setBounds(70, 80, 100, 30);

        labelCustom3.setText("ID Grupo");
        jPanel1.add(labelCustom3);
        labelCustom3.setBounds(70, 200, 100, 30);

        IDGrupo_Abate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDGrupo_AbateActionPerformed(evt);
            }
        });
        jPanel1.add(IDGrupo_Abate);
        IDGrupo_Abate.setBounds(180, 200, 170, 30);
        jPanel1.add(PesoAbate_Abate);
        PesoAbate_Abate.setBounds(180, 260, 170, 30);

        labelCustom4.setText("ID Animal");
        jPanel1.add(labelCustom4);
        labelCustom4.setBounds(70, 140, 100, 30);

        labelCustom5.setText("labelCustom5");
        jPanel1.add(labelCustom5);
        labelCustom5.setBounds(180, 80, 170, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário Abate");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 240, 40);

        panelImage1.add(jPanel1);
        jPanel1.setBounds(40, 40, 430, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(660, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDAnimal_AbateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDAnimal_AbateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDAnimal_AbateActionPerformed

    private void IDGrupo_AbateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDGrupo_AbateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDGrupo_AbateActionPerformed

    private void voltarAbateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAbateActionPerformed
       Abate_GUI.this.dispose();
    }//GEN-LAST:event_voltarAbateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDAnimal_Abate;
    private javax.swing.JTextField IDGrupo_Abate;
    private javax.swing.JFormattedTextField PesoAbate_Abate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.label.LabelCustom labelCustom2;
    private org.edisoncor.gui.label.LabelCustom labelCustom3;
    private org.edisoncor.gui.label.LabelCustom labelCustom4;
    private org.edisoncor.gui.label.LabelCustom labelCustom5;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.button.ButtonAero voltarAbate;
    // End of variables declaration//GEN-END:variables
}
