/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author LAB4M10
 */
public class Vacinados_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Vacinados_GUI
     */
    public Vacinados_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        voltarAbate = new org.edisoncor.gui.button.ButtonAero();
        jPanel1 = new javax.swing.JPanel();
        PesoAbate_Label = new org.edisoncor.gui.label.LabelCustom();
        IDAnimal_Abate = new javax.swing.JTextField();
        IDVacinaVac_Label = new org.edisoncor.gui.label.LabelCustom();
        VacinadoVac_Label = new org.edisoncor.gui.label.LabelCustom();
        Vacinado_Vac = new javax.swing.JTextField();
        IDAnimalAbate_Label = new org.edisoncor.gui.label.LabelCustom();
        IDAbate_Mostra = new org.edisoncor.gui.label.LabelCustom();
        jLabel1 = new javax.swing.JLabel();
        IDAbate_Label1 = new org.edisoncor.gui.label.LabelCustom();
        IDAnimalAbate_Label1 = new org.edisoncor.gui.label.LabelCustom();
        IDAnimal_Abate2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fundo2.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        voltarAbate.setText("Voltar");
        voltarAbate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAbateActionPerformed(evt);
            }
        });
        panelImage1.add(voltarAbate);
        voltarAbate.setBounds(560, 360, 80, 25);

        jPanel1.setLayout(null);

        PesoAbate_Label.setText("Data");
        jPanel1.add(PesoAbate_Label);
        PesoAbate_Label.setBounds(10, 250, 80, 30);

        IDAnimal_Abate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDAnimal_AbateActionPerformed(evt);
            }
        });
        jPanel1.add(IDAnimal_Abate);
        IDAnimal_Abate.setBounds(100, 130, 120, 30);

        IDVacinaVac_Label.setText("IDVacina");
        jPanel1.add(IDVacinaVac_Label);
        IDVacinaVac_Label.setBounds(10, 70, 80, 30);

        VacinadoVac_Label.setText("Vacinado");
        jPanel1.add(VacinadoVac_Label);
        VacinadoVac_Label.setBounds(10, 190, 80, 30);

        Vacinado_Vac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vacinado_VacActionPerformed(evt);
            }
        });
        jPanel1.add(Vacinado_Vac);
        Vacinado_Vac.setBounds(100, 190, 120, 30);

        IDAnimalAbate_Label.setText("ID Animal");
        jPanel1.add(IDAnimalAbate_Label);
        IDAnimalAbate_Label.setBounds(10, 130, 80, 30);

        IDAbate_Mostra.setText("labelCustom5");
        jPanel1.add(IDAbate_Mostra);
        IDAbate_Mostra.setBounds(100, 70, 120, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário Vacina");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 10, 240, 40);

        IDAbate_Label1.setText("Ocorrência");
        jPanel1.add(IDAbate_Label1);
        IDAbate_Label1.setBounds(240, 160, 80, 30);

        IDAnimalAbate_Label1.setText("Tipo Vacina");
        jPanel1.add(IDAnimalAbate_Label1);
        IDAnimalAbate_Label1.setBounds(240, 70, 80, 30);

        IDAnimal_Abate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDAnimal_Abate2ActionPerformed(evt);
            }
        });
        jPanel1.add(IDAnimal_Abate2);
        IDAnimal_Abate2.setBounds(330, 70, 120, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 160, 166, 100);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(100, 250, 120, 30);

        panelImage1.add(jPanel1);
        jPanel1.setBounds(40, 40, 510, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(660, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarAbateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAbateActionPerformed
        Vacinados_GUI.this.dispose();
    }//GEN-LAST:event_voltarAbateActionPerformed

    private void IDAnimal_AbateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDAnimal_AbateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDAnimal_AbateActionPerformed

    private void Vacinado_VacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vacinado_VacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vacinado_VacActionPerformed

    private void IDAnimal_Abate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDAnimal_Abate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDAnimal_Abate2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vacinados_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vacinados_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vacinados_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vacinados_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vacinados_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.label.LabelCustom IDAbate_Label1;
    private org.edisoncor.gui.label.LabelCustom IDAbate_Mostra;
    private org.edisoncor.gui.label.LabelCustom IDAnimalAbate_Label;
    private org.edisoncor.gui.label.LabelCustom IDAnimalAbate_Label1;
    private javax.swing.JTextField IDAnimal_Abate;
    private javax.swing.JTextField IDAnimal_Abate2;
    private org.edisoncor.gui.label.LabelCustom IDVacinaVac_Label;
    private org.edisoncor.gui.label.LabelCustom PesoAbate_Label;
    private org.edisoncor.gui.label.LabelCustom VacinadoVac_Label;
    private javax.swing.JTextField Vacinado_Vac;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.button.ButtonAero voltarAbate;
    // End of variables declaration//GEN-END:variables
}
